Revert "Attempt to enable webxr passthrough"
This reverts commit 1a2f229c25486153301aff4dcdd133dec40a0fa8.

TypeError: renderer.xr is undefined, probably because Three.js is
too old.